-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
SUM(`purchase_amount_(usd)`) as revenue 
FROM customers
group by gender
;
-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,
`purchase_amount_(usd)`
from customers
where discount_applied = "Yes" and `purchase_amount_(usd)` >= (SELECT avg(`purchase_amount_(usd)`) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as avg_product_rating
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select 
shipping_type,
round(avg(`purchase_amount_(usd)`),2) as average_Purchase_Amounts
from customers
where shipping_type in ("Express","Standard")
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select 
subscription_status,
count(customer_id) total_customers,
round(avg(`purchase_amount_(usd)`),2) avg_spent,
round(sum(`purchase_amount_(usd)`),2) total_revenue
from customers
GROUP BY subscription_status
order by total_revenue,avg_spent desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
item_purchased,
round(100*sum(case when discount_applied = "Yes" then 1 else 0 end )/count(*),2) as discount_rate
from customers
GROUP BY item_purchased 
ORDER BY discount_rate desc
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT 
customer_id,
previous_purchases,
case when previous_purchases = 1 then "New"
when previous_purchases BETWEEN 2 and 10 then "Returning"
else "Loyal" 
end as customer_segment
from customers
)
SELECT 
customer_segment,
COUNT(*) no_of_cust
from customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with items_count as (
SELECT 
category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(PARTITION BY  category ORDER BY count(customer_id) desc) as item_rnk
from customers
GROUP BY category,item_purchased
)
SELECT item_rnk,category,item_purchased,total_orders
from items_count
where item_rnk <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
GROUP BY subscription_status;
-- Q10. What is the revenue contribution of each age group? 
SELECT 
age_group,
sum(`purchase_amount_(usd)`) as revenue
from customers
group by age_group
order by revenue desc


